
linux-amd64-build:
    stage: build
    image: $CI_REGISTRY/mono/mono:debian-trixie-linux-build
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PROJECT_NAMESPACE == 'mono'
    interruptible: true
    cache:
        -
            key: $CI_JOB_NAME-ccache
            paths:
                - ccache/
    before_script:
        - export BASEDIR="$PWD"
        - export CCACHE_BASEDIR="$BASEDIR"
        - export CCACHE_DIR="$BASEDIR/ccache"
        - export CCACHE_COMPILERCHECK=content
        - export PATH="/usr/lib/ccache:$PATH"
        - git config --global --add safe.directory $CI_PROJECT_DIR
        - rm -fr .git/rebase-merge  # in case a previous CI run failed in git rebase
    script:
        - "scripts/ci/update-submodules.sh"
        - "scripts/ci/build.sh"
    artifacts:
        paths:
            - test-bundle/
            - mcs/class/monolite-*.tar.gz
        expire_in: 1 week

build-dist:
    stage: build
    image: $CI_REGISTRY/mono/mono:debian-trixie-linux-build
    when: manual
    interruptible: true
    before_script:
        - export BASEDIR="$PWD"
        - export PATH="/usr/lib/ccache:$PATH"
        - git config --global --add safe.directory $CI_PROJECT_DIR
        - rm -fr .git/rebase-merge  # in case a previous CI run failed in git rebase
    script:
        - "scripts/ci/update-submodules.sh"
        - "./autogen.sh"
        - "make all"
        - "make -j1 dist"
    artifacts:
        paths:
            - mono-*.tar.xz
        expire_in: 1 week
