thisdir = tools/al
SUBDIRS = 
include ../../build/rules.make

LOCAL_MCS_FLAGS =
LIB_REFS = System System.Core WineMono.Security System.Security WineMono.CompilerServices.SymbolWriter
PROGRAM = al.exe

CLEAN_FILES = al.exe al.exe.mdb

include ../../build/executable.make
