thisdir = class/I18N/Common
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = WineMono.I18N.dll
KEYFILE = ../../mono.pub
LOCAL_MCS_FLAGS = /unsafe /define:DISABLE_UNSAFE
NO_TEST = yes

include ../../../build/library.make
