thisdir = class/I18N/Other
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = WineMono.I18N.Other.dll
LIB_REFS = WineMono.I18N
KEYFILE = ../../mono.pub
LOCAL_MCS_FLAGS = /unsafe
TEST_LIB_REFS = WineMono.I18N

EXTRA_DISTFILES = $(wildcard *.ucm)

include ../../../build/library.make
