thisdir = class/System.Data.Entity.Design
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Data.Entity.Design.dll
LIB_REFS = System System.Core System.Data System.Data.DataSetExtensions System.Data.Entity System.Web System.Xml System.Xml.Linq
KEYFILE = ../ecma.pub
LIB_MCS_FLAGS = -warn:2

TXT_RESOURCE_STRINGS = ../referencesource/System.Data.Entity.Design/System.Data.Entity.Design.txt

include ../../build/library.make
