thisdir = tools/pdb2mdb
SUBDIRS =
include ../../build/rules.make

PROGRAM = pdb2mdb.exe

LOCAL_MCS_FLAGS =
LIB_REFS = Mono.Cecil WineMono.CompilerServices.SymbolWriter System.Core


EXTRA_DISTFILES = LICENSE

include ../../build/executable.make
