thisdir = class/System.Deployment
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Deployment.dll

LIB_REFS = System
LIB_MCS_FLAGS = -delaysign -keyfile:../msfinal.pub

include ../../build/library.make
